### ISSUE TITLE
Could you upload the Decoder section of source code

### ISSUE THREAD

**Issue by Aki-Tomoya** [lzp870/RSFD#1]
Hello! After reading your team's paper, I was deeply inspired, and I think it is a very excellent model!Now I want to study the model you proposed more carefully, so I want to read the source code of the Decoder part. I wonder if you can improve the repositories of RSFD?You can contact me at my email address: akitomoya10032@163.com

**Comment by Aki-Tomoya** [comment]
nice work. /w\

**Comment by Jack2Lu** [comment]
> nice work. /w\

Hello, I want to reproduce this work recently but find 'loss_result' not defined in 'misc/crit.py'. Have you contacted with author? If possible, please info me how to caculate 'loss_result'. I would be grateful.
